server {
  listen 8080;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: adjust caching headers for static files
  location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff2?)$ {
    expires 30d;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
  }


    access_log off;
    error_log  /var/log/nginx/error.log warn;
}
